
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/database_ismi # Gerçek database ismi ile değiştir
    username: your_db_username # Database username ile değiştir
    password: your_db_password # Database password'u ile değiştir
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  # Elasticsearch configuration
  data:
    elasticsearch:
      client:
        reactive:
          endpoints: localhost:9200 # Elasticsearch host ve port ile değiştir eğer farklı ise